import enum


class PacketTCPCoordinatorType(enum.IntEnum):
    PACKET_COORDINATOR_SERVER_ERROR = 0
    PACKET_COORDINATOR_CLIENT_REGISTER = 1
    PACKET_COORDINATOR_SERVER_REGISTER_ACK = 2
    PACKET_COORDINATOR_CLIENT_UPDATE = 3
    PACKET_COORDINATOR_CLIENT_LISTING = 4
    PACKET_COORDINATOR_SERVER_LISTING = 5
    PACKET_COORDINATOR_CLIENT_CONNECT = 6
    PACKET_COORDINATOR_SERVER_CONNECTING = 7
    PACKET_COORDINATOR_CLIENT_CONNECT_FAILED = 8
    PACKET_COORDINATOR_SERVER_CONNECT_FAILED = 9
    PACKET_COORDINATOR_CLIENT_CONNECTED = 10
    PACKET_COORDINATOR_SERVER_DIRECT_CONNECT = 11
    PACKET_COORDINATOR_SERVER_STUN_REQUEST = 12
    PACKET_COORDINATOR_SERVER_STUN_CONNECT = 13
    PACKET_COORDINATOR_CLIENT_STUN_RESULT = 14
    PACKET_COORDINATOR_SERVER_TURN_CONNECT = 15
    PACKET_COORDINATOR_END = 16


class PacketTCPStunType(enum.IntEnum):
    PACKET_STUN_CLIENT_STUN = 0
    PACKET_STUN_END = 1


class PacketTCPTurnType(enum.IntEnum):
    PACKET_TURN_SERVER_ERROR = 0
    PACKET_TURN_CLIENT_CONNECT = 1
    PACKET_TURN_SERVER_CONNECTED = 2
    PACKET_TURN_END = 3


class ServerGameType(enum.IntEnum):
    SERVER_GAME_TYPE_LOCAL = 0
    SERVER_GAME_TYPE_PUBLIC = 1
    SERVER_GAME_TYPE_INVITE_ONLY = 2
    SERVER_GAME_TYPE_END = 3


class NetworkCoordinatorErrorType(enum.IntEnum):
    NETWORK_COORDINATOR_ERROR_UNKNOWN = 0
    NETWORK_COORDINATOR_ERROR_REGISTRATION_FAILED = 1
    NETWORK_COORDINATOR_ERROR_INVALID_JOIN_KEY = 2


class ConnectionType(enum.IntEnum):
    CONNECTION_TYPE_UNKNOWN = 0
    CONNECTION_TYPE_ISOLATED = 1
    CONNECTION_TYPE_DIRECT = 2
    CONNECTION_TYPE_STUN = 3
    CONNECTION_TYPE_TURN = 4
